# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Julian Frattini
tagline:          'Personal Website'
description:      'Ph.D. Student at the <a href="https://www.bth.se/eng/" target="_blank">Blekinge Institute of Technology</a> conducting Empirical Research on Requirements Quality.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Julian Frattini'
  url:            https://x.com/frattinij1

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/JulianFrattini/JulianFrattini.github.io
