# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Julian Frattini
tagline:          'Ph.D. Student at the Blekinge Institute of Technology'
description:      'Ph.D. Student at the <a href="https://www.bth.se/eng/" target="_blank">Blekinge Institute of Technology</a>'
url:              https://julianfrattini.github.io
baseurl:          /

author:
  name:           'Julian Frattini'
  url:            https://x.com/frattinij1

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/JulianFrattini/JulianFrattini.github.io
